name: Docker Image pba_back
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v3
    - name: "Creation de l'image pba dev"
      run: docker build . --file Dockerfile --tag gh-run:dev
    - name: "run"
      run: docker run -p 95:5000 gh-run:dev 
